import pandas as pd
import re

def is_trivial_comment(comment):
    # Remove comment markers
    clean = re.sub(r'/\*\*|\*/|\*|//', '', comment).strip().lower()
    
    # List of trivial patterns
    trivial_phrases = [
        'todo', 'fixme', 'bug', 'auto-generated', 'generated by',
        'licensed under', 'copyright', 'internal', 'debugger',
        'var_dump', 'console.log'
    ]
    
    if len(clean.split()) < 3: # Too short
        return True
        
    for phrase in trivial_phrases:
        if phrase in clean:
            return True
            
    return False

def clean_dataset(df):
    # 1. Remove duplicates
    df = df.drop_duplicates(subset=['code'])
    
    # 2. Filter trivial comments
    df = df[~df['comment'].apply(is_trivial_comment)]
    
    # 3. Basic formatting
    df['comment'] = df['comment'].apply(lambda x: re.sub(r'/\*\*|\*/|\*|//', '', x).strip())
    
    return df

if __name__ == "__main__":
    import os
    print("Reading extracted combined dataset...")
    df = pd.read_csv("data/raw/extracted_combined.csv")
    print(f"Initial count: {len(df)}")
    
    df_cleaned = clean_dataset(df)
    print(f"Cleaned count: {len(df_cleaned)}")
    
    os.makedirs("data/processed", exist_ok=True)
    df_cleaned.to_csv("data/processed/cleaned_pairs.csv", index=False)
    print(f"Results saved to data/processed/cleaned_pairs.csv")
